# Generated by Django 4.2.3 on 2023-09-24 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='createdAt',
        ),
    ]
